name: easy_localization_cleaner
description: >-
  A Dart CLI tool designed to clean up unused localization keys from JSON/Arb files used with the easy_localization package.
version: 0.0.3
homepage: https://github.com/thanhhaidev/easy_localization_cleaner

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  easy_localization_cleaner: main

dependencies:
  analyzer: ^7.3.0
  args: ^2.7.0
  glob: ^2.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  very_good_analysis: ^7.0.0
